export const PROSPECTION_PHRASES = [
  "je me permets de vous contacter",
  "je me permets de revenir vers vous",
  "notre solution permet",
  "augmenter votre chiffre d'affaires",
  "augmenter votre ca",
  "proposition de partenariat",
  "referencement de votre etablissement",
  "nous accompagnons les restaurants",
  "rendez-vous telephonique",
  "15 minutes de votre temps",
  "quelques minutes de votre temps",
  "demo de notre outil",
  "demo de notre solution",
  "optimiser votre gestion",
  "solution dediee aux restaurants",
  "booster vos ventes",
  "developper votre visibilite",
  "nous proposons aux restaurateurs",
  "je reviens vers vous suite a mon precedent",
  "sauf erreur de ma part",
]

export const EVENT_KEYWORDS = {
  strong: [
    'privatisation', 'privatiser', 'privatif', 'privatisez',
    'mariage', 'nous marions', 'se marier',
    'bapteme', 'baptiser',
    'evjf', 'evg', 'enterrement de vie',
    "comite d'entreprise", 'comite dentreprise',
    'cse',
    'seminaire', 'team building', 'teambuilding',
    'cocktail dinatoire',
    'buffet privatise',
    'reception privee',
    'soiree privee',
    'devis groupe', 'tarif groupe', 'tarifs groupe',
    'rotary', 'lions club', 'kiwanis',
  ],
  medium: [
    'evenement',
    'anniversaire', 'feter',
    'organiser', 'reserver',
    'groupe de', 'pour nous', 'pour notre',
    "repas d'entreprise", 'repas dentreprise',
    "repas d'affaires",
    "diner d'entreprise", 'diner dentreprise',
    'association', 'reunion',
  ],
}
